import { useEffect, useState } from 'react';
import apiClient from '../lib/api';
import { Field, FormSection, Page } from './AdminPrimitives';

export default function Settings() {
  const [saved, setSaved] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({});
  useEffect(() => { apiClient.get('/admin/settings').then(({ data }) => setForm(data.data || {})).catch(() => setError('Unable to load settings.')); }, []);
  const update = (event) => { const { name, type, value, checked } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })); setSaved(false); };
  const save = async () => { try { await apiClient.put('/admin/settings', form); setSaved(true); } catch { setError('Unable to save settings.'); } };
  return <Page title="Settings" description="Store configuration and Razorpay dummy gateway settings."><div className="settings-stack"><FormSection title="Business"><Field label="Business name"><input name="businessName" value={form.businessName || ''} onChange={update} /></Field><Field label="Business email"><input name="businessEmail" type="email" value={form.businessEmail || ''} onChange={update} /></Field><Field label="Business phone"><input name="businessPhone" value={form.businessPhone || ''} onChange={update} /></Field><Field label="Business address"><textarea name="businessAddress" rows="3" value={form.businessAddress || ''} onChange={update} /></Field></FormSection><FormSection title="Store"><Field label="Currency"><select name="currency" value={form.currency || 'INR'} onChange={update}><option>INR</option><option>USD</option></select></Field><Field label="Default shipping charge"><input name="shippingCharge" type="number" value={form.shippingCharge || ''} onChange={update} /></Field><Field label="Low-stock threshold"><input name="lowStockThreshold" type="number" value={form.lowStockThreshold || ''} onChange={update} /></Field></FormSection><FormSection title="Payments"><Field label="Gateway"><select name="paymentGateway" value={form.paymentGateway || 'razorpay_dummy'} onChange={update}><option value="razorpay_dummy">Razorpay dummy</option></select></Field><Field label="Razorpay key ID"><input name="razorpayKeyId" value={form.razorpayKeyId || ''} onChange={update} /></Field><Field label="Razorpay key secret"><input name="razorpayKeySecret" type="password" value={form.razorpayKeySecret || ''} onChange={update} /></Field></FormSection><FormSection title="Notifications"><Field label="Email notifications"><input name="emailNotifications" type="checkbox" checked={form.emailNotifications ?? true} onChange={update} /></Field><Field label="SMS notifications"><input name="smsNotifications" type="checkbox" checked={form.smsNotifications ?? true} onChange={update} /></Field></FormSection><button className="primary-button" onClick={save}>Save settings</button>{error && <span className="save-message" role="alert">{error}</span>}{saved && <span className="save-message">Settings saved to the backend.</span>}</div></Page>;
}